Repository line/centraldogma-go, pull requests merged in 2019-04, with the labels that each got.

#26 Fix to handle 304 when watching
  content_service.go
  content_service_test.go
  dogma.go
  dogma_test.go
  project_service.go
  project_service_test.go
  repository_service.go
  repository_service_test.go
  watch_service.go
  watch_service_test.go
Labels: defect

#25 Adapt CLI App and update README
  README.md
  go.mod
  go.sum
  internal/app/dogma/go.mod
  internal/app/dogma/go.sum
Labels: documentation

#27 NO-ISSUE Optimize watch service
  watch_service.go
Labels: improvement
